### ISSUE TITLE
IAM Service with self managed certificate

### ISSUE THREAD

**Issue by reiinoldo** [philips-software/provider-hsdp#220]
When I'm controlling the Service certificate generation and setting the value on the `selfManagedPrivateKeySecretRef` it's not applying it but it's using it's own generated default certificate.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xiamservices.pics.crossplane.io
  labels:
    pics.crossplane.io/provider: hsdp
spec:
  compositeTypeRef:
    apiVersion: pics.crossplane.io/v1alpha1
    kind: XIamService
  mode: Pipeline  
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: hsp-addons  
    - step: create-resources
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: common-fields
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.deletionPolicy
                toFieldPath: spec.deletionPolicy
        resources:
          - name: certificate
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: cert-manager.io/v1
                    kind: Certificate
                    spec:
                      isCA: false
                      duration: 2160h
                      renewBefore: 1h  
                      privateKey:
                        rotationPolicy: Always
                        algorithm: RSA
                        size: 4096
                      dnsNames: []
            patches:
              - type: PatchSet
                patchSetName: common-fields
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.certificate.duration
                toFieldPath: spec.forProvider.manifest.spec.duration
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.certificate.issuerRef
                toFieldPath: spec.forProvider.manifest.spec.issuerRef
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.certificate.rotationPolicy
                toFieldPath: spec.forProvider.manifest.spec.privateKey.rotationPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.certificate.secretRef.name
                toFieldPath: spec.forProvider.manifest.spec.secretName
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.manifest.metadata.namespace              
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.forProvider.service.name
                    - fromFieldPath: spec.forProvider.certificate.dnsSuffix
                  strategy: string
                  string:
                    fmt: "%s.%s"
                toFieldPath: spec.forProvider.manifest.spec.commonName
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.forProvider.service.name
                    - fromFieldPath: spec.forProvider.certificate.dnsSuffix
                  strategy: string
                  string:
                    fmt: "%s.%s"
                toFieldPath: spec.forProvider.manifest.spec.dnsNames[0]

          - name: service
            base:
              apiVersion: iam.hsdp.crossplane.io/v1alpha1
              kind: Service
              spec:
                forProvider:
                  description: "This resource is managed by Crossplane. Do not modify it manually."
                  scopes:
                    - "openid"
                    - "code"
                  defaultScopes:
                    - "openid"
                  selfManagedPrivateKeySecretRef:
                    key: tls.key
            patches:
              - type: PatchSet
                patchSetName: common-fields
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.name
                toFieldPath: spec.forProvider.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.applicationId
                toFieldPath: spec.forProvider.applicationId
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.description
                toFieldPath: spec.forProvider.description
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.scopes
                toFieldPath: spec.forProvider.scopes
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.defaultScopes
                toFieldPath: spec.forProvider.defaultScopes
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.service.tokenValidity
                toFieldPath: spec.forProvider.tokenValidity
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.certificate.secretRef.name
                toFieldPath: spec.forProvider.selfManagedPrivateKeySecretRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.forProvider.providerConfigRefName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.forProvider.selfManagedPrivateKeySecretRef.namespace
              - fromFieldPath: spec.forProvider.certificate.secretRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      fmt: "%s-writeconnectionsecrettoref-secret"
                      type: Format
              - fromFieldPath: metadata.labels["crossplane.io/claim-namespace"]
                toFieldPath: spec.writeConnectionSecretToRef.namespace

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
```

See the ouput for the connection secrect created: 

![Image](https://github.com/user-attachments/assets/73bad72f-6075-4dbf-a5a7-2a09773143d8)

The `self_managed_private_key` is empty, but the `private_key` not. 
The certificate is being created correctly.
The link between the service and certificate are ok. 
I'm using a self-signed cluster issuer.
If I manually insert (via IAM UI) the certificate generated then I'm able to authenticate with the service. Otherwise I only get `Invalid_client / Invalid JWT has expired or is not valid`
Also, if I use the `private_key` to authenticate with the service then it works.
